name: Auto Update Job Calendar

on:
  workflow_dispatch:  # 수동 실행을 활성화
  schedule:
    - cron: "0 9 * * *"  # 매일 오전 9시에 자동 실행

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Job Postings
        run: python update_jobs.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "자동 업데이트: 최신 개발자 공고"
          git push
